apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  ports:
  - name: "8081"
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mongo
  type: ClusterIP
status:
  loadBalancer: {}
