apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-6-auth-server
  name: spring-6-auth-server
spec:
  ports:
  - name: "9000"
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: spring-6-auth-server
  type: ClusterIP
status:
  loadBalancer: {}
