apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-6-reactive
  name: spring-6-reactive
spec:
  ports:
  - name: "8082"
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: spring-6-reactive
  type: ClusterIP
status:
  loadBalancer: {}
