apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-6-gateway
  name: spring-6-gateway
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-6-gateway
  type: NodePort
status:
  loadBalancer: {}
