apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-6-reactive-mongo
  name: spring-6-reactive-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-6-reactive-mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-6-reactive-mongo
    spec:
      containers:
      - image: sadatmalik/spring-6-reactive-mongo
        name: spring-6-reactive-mongo
        resources: {}
        env:
          - name: LOGGING_LEVEL_COM_CREATIVEFUSION
            value: debug
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
            value: http://spring-6-auth-server:9000
        readinessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 10" ]
status: {}
