apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-6-gateway
  name: spring-6-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-6-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-6-gateway
    spec:
      containers:
      - image: sadatmalik/spring-6-gateway
        name: spring-6-gateway
        resources: {}
        env:
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
            value: http://spring-6-auth-server:9000
status: {}
