apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-6-rest-mvc
  name: spring-6-rest-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-6-rest-mvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-6-rest-mvc
    spec:
      containers:
      - image: sadatmalik/spring-6-rest-mvc
        name: spring-6-rest-mvc
        resources: {}
        env:
          - name: LOGGING_LEVEL_COM_CREATIVEFUSION
            value: info
status: {}
