apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-6-rest-mvc
  name: spring-6-rest-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-6-rest-mvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-6-rest-mvc
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs.json-logging/json.keys_under_root: "true"
        co.elastic.logs.json-logging/json.add_error_key: "true"
        co.elastic.logs.json-logging/json.message_key: "message"
    spec:
      containers:
      - image: sadatmalik/spring-6-rest-mvc
        name: spring-6-rest-mvc
        resources: {}
        env:
          - name: LOGGING_LEVEL_COM_CREATIVEFUSION
            value: info
        readinessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 10" ]
status: {}
