apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-6-rest-mvc
  name: spring-6-rest-mvc
spec:
  ports:
  - name: "8081"
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: spring-6-rest-mvc
  type: ClusterIP
status:
  loadBalancer: {}
