# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      - my-sql:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  spring-6-rest-mvc:
    image: sadatmalik/spring-6-rest-mvc
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8081:8081

  spring-6-gateway:
    image: sadatmalik/spring-6-gateway
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - spring-6-rest-mvc

volumes:
  my-sql:
